//
// Created by lutyk on 14.04.24.
//

#ifndef LAB7_WORDS_COUNT_UNICODE_SAMOILENKO_PELEKH_YARISH_MASTER_ERRORS_H
#define LAB7_WORDS_COUNT_UNICODE_SAMOILENKO_PELEKH_YARISH_MASTER_ERRORS_H

enum errors{
    SUCCESS = 0,
    INCORRECT_ARGS = 1,
    CONFIGURATION_OPEN_FAILED = 3,
    WRITEFILE_OPEN_FAILED = 4,
    CONFIGURATION_READ_FAILED = 5,
    WRITE_FAILED = 6,
    ABSENT_DIR = 26,
    FILE_OPEN_FAILED = 64
};


#endif //LAB7_WORDS_COUNT_UNICODE_SAMOILENKO_PELEKH_YARISH_MASTER_ERRORS_H
